[package]
name = "tom-servo"
version = "0.1.0"
authors = ["James Hobin <hobinjk@gmail.com>"]

[dependencies]
webthing = { git = "https://github.com/mozilla-iot/webthing-rust" }
i2cdev = "0.4.0"
serde_json = "1.0"

[[bin]]
name = "tom-servo"
path = "main.rs"
